# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.  Look in ~/.oh-my-zsh/themes/ Optionally, if
# you set this to "random", it'll load a random theme each time that oh-my-zsh
# is loaded.
# ZSH_THEME="random"
# ZSH_THEME="rgm"
ZSH_THEME="dieter"

# Example aliases alias zshconfig="mate ~/.zshrc" alias ohmyzsh="mate
# ~/.oh-my-zsh"

# Set to this to use case-sensitive completion CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days) export
# UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting
# for completion COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.  DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time
# stamp in the history command output. The optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"| yyyy-mm-dd HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in
# ~/.oh-my-zsh/plugins/*) Custom plugins may be added to
# ~/.oh-my-zsh/custom/plugins/ Example format: plugins=(rails git textmate ruby
# lighthouse)
plugins=(git svn ruby osx emoji-clock encode64 themes xcode)

source $ZSH/oh-my-zsh.sh

# User configuration
# bindkey -v
# bindkey '^R' history-incremental-search-backward

export PATH="/usr/local/bin:usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:"
# export MANPATH="/usr/local/man:$MANPATH"
export QUICK_COCOS2DX_ROOT=~/Documents/programming/code/quick-cocos2d-x
export COCOS2DX_ROOT=${QUICK_COCOS2DX_ROOT}/lib/cocos2d-x
export CODE=/Users/imbahom_mbp/Documents/programming/code
export TIPS=$CODE/myKnowledgeTips
# for golang
export GOPATH=$CODE/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
# specify that it must be pressed twice to exit:
export IGNOREEOF=1

LANG=zh_CN.UTF-8
# LANG=zh_CN
export LANG

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then export EDITOR='vim' else export EDITOR='mvim'
fi

#ec2-api-tool
# export JAVA_HOME="$(/usr/libexec/java_home)"
# export AWS_ACCESS_KEY="AKIAJVEYNE5OZKTB2BWQ"
# export AWS_SECRET_KEY="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"
# export EC2_HOME="/usr/local/Cellar/ec2-api-tools/1.6.13.0/libexec"
# export EC2_AMITOOL_HOME="/usr/local/Cellar/ec2-ami-tools/1.5.2/libexec"

# Compilation flags export ARCHFLAGS="-arch x86_64"

# ssh export SSH_KEY_PATH="~/.ssh/dsa_id"
#
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

alias rm="trash"

