# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.  Look in ~/.oh-my-zsh/themes/ Optionally, if
# you set this to "random", it'll load a random theme each time that oh-my-zsh
# is loaded.
# ZSH_THEME="random"
ZSH_THEME="rgm"
# ZSH_THEME="dieter"

# Example aliases alias zshconfig="mate ~/.zshrc" alias ohmyzsh="mate
# ~/.oh-my-zsh"

# Set to this to use case-sensitive completion CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days) export
# UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting
# for completion COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.  DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time
# stamp in the history command output. The optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"| yyyy-mm-dd HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in
# ~/.oh-my-zsh/plugins/*) Custom plugins may be added to
# ~/.oh-my-zsh/custom/plugins/ Example format: plugins=(rails git textmate ruby
# lighthouse)
plugins=(git svn git_imbahom svn_imbahom ruby osx emoji-clock encode64 themes xcode vagrant)

source $ZSH/oh-my-zsh.sh

# User configuration
# using vi mode in zsh
# bindkey -v

# bindkey '^R' history-incremental-search-backward

export PATH=~/bin:/usr/local/bin:usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
export CODE=~/Documents/programming/code
# export MANPATH="/usr/local/man:$MANPATH"
export QUICK_V3_ROOT=`cat ~/.QUICK_V3_ROOT`

# export ANDROID_SDK_ROOT=$CODE/dev_env/android_sdk
export ANDROID_SDK_ROOT=~/Library/Android/sdk
export ANDROID_HOME=$ANDROID_SDK_ROOT
export NDK_ROOT=$CODE/dev_env/NDK/android-ndk-r9b
export ANDROID_NDK_ROOT=$NDK_ROOT

# for golang
export GOPATH=$CODE/dev_env/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
# specify that it must be pressed twice to exit:
export IGNOREEOF=1

LANG=zh_CN.UTF-8
# LANG=zh_CN
export LANG

export TERM=xterm-256color

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then export EDITOR='vim' else export EDITOR='mvim'
fi

# Compilation flags export ARCHFLAGS="-arch x86_64"

# ssh export SSH_KEY_PATH="~/.ssh/dsa_id"
#
# export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

alias rm="trash"
alias netspeed="vnstat -l -i en0"
alias myscp='rsync --progress --partial --av'

# exec > >(tee -a ~/$$.out)
# PROMPT_COMMAND='LASTLINE=$(tail -n 1 ~/$$.out)'
# trap 'rm ~/$$.out' EXIT

alias tma="tmux attach"
function startWork(){
cmd="'cd $CODE/Project2/trunk/Developer/client/scripts && vim **/*.lua'"
python ~/.dotfiles/zsh/startWork.py $cmd
}

function vpn-connect {
/usr/bin/env osascript <<-EOF
tell application "System Events"
        tell current location of network preferences
                set VPN to service "imbahom_do" -- your VPN name here
                if exists VPN then connect VPN
                repeat while (current configuration of VPN is not connected)
                    delay 1
                end repeat
        end tell
end tell
EOF
}

function vpn-disconnect {
/usr/bin/env osascript <<-EOF
tell application "System Events"
        tell current location of network preferences
                set VPN to service "imbahom_do" -- your VPN name here
                if exists VPN then disconnect VPN
        end tell
end tell
return
EOF
}


